name: Acquire activation file
on: [push]
jobs:
  activation:
    name: Request manual activation file
    runs-on: ubuntu-latest
    steps:
    - name: Request manual activation file
      id: editor-2019.4.20f1-0.11.0
      uses: game-ci/unity-request-activation-file@v2
    - run: echo ${{ steps.getManualLicenseFile.outputs.filePath }}
